from kmk.keys import KC
# ARGH time to swap this back into cykey (maybe. someday.)
class DVP():
    def __init__(self):
        self.keys = {
            'A': KC.A,
            'AMPR': KC.AMPR,
            'ASTR': KC.ASTR,
            'AT': KC.AT,
            'AUDIO_VOL_DOWN': KC.AUDIO_VOL_DOWN,
            'AUDIO_VOL_UP': KC.AUDIO_VOL_UP,
            'B': KC.N,
            'BRIGHTNESS_DOWN': KC.BRIGHTNESS_DOWN,
            'BRIGHTNESS_UP': KC.BRIGHTNESS_UP,
            'BSLS': KC.BSLS,
            'BSPC': KC.BSPC,
            'C': KC.I,
            'CIRC': KC.CIRC, # ^
            'COLN': KC.LSFT(KC.Z), # uhhhh does this work? since it's a shifted key
            'COMM': KC.W,
            'D': KC.H,
            'DEL': KC.DEL,
            'DLR': KC.DLR,
            'DOT': KC.E,
            'DOWN': KC.DOWN,
            'DQT': KC.LSFT(KC.Q),# doublequote - but it's shifted... TODO
            'E': KC.D,
            'END': KC.END,
            'ENTER': KC.ENTER,
            'EQL': KC.RBRACKET,
            'ESC': KC.ESC,
            'EXLM': KC.EXLM, # ? 
            'F': KC.Y,
            'F1': KC.F1,
            'F10': KC.F10,
            'F11': KC.F11,
            'F12': KC.F12,
            'F2': KC.F2,
            'F3': KC.F3,
            'F4': KC.F4,
            'F5': KC.F5,
            'F6': KC.F6,
            'F7': KC.F7,
            'F8': KC.F8,
            'F9': KC.F9,
            'G': KC.U,
            'GRV': KC.GRV,
            'H': KC.J,
            'HASH': KC.HASH,
            'HOME': KC.HOME,
            'I': KC.G,
            'INS': KC.INS,
            'J': KC.C,
            'K': KC.V,
            'L': KC.P,
            'LABK': KC.LABK,
            'LALT': KC.LALT,
            'LAYER0': KC.LAYER0,
            'LAYER1': KC.LAYER1,
            'LAYER2': KC.LAYER2,
            'LAYER3': KC.LAYER3,
            'LBRC': KC.LBRC,
            'LCBR': KC.LCBR,
            'LCTL': KC.LCTL,
            'LEFT': KC.LEFT,
            'LGUI': KC.LGUI,
            'LPRN': KC.LPRN,
            'LSFT': KC.LSFT,
            'M': KC.M,
            'MINS': KC.QUOTE, # minus
            'MOD_AC': KC.MOD_AC, # ARGH this isn't defined yet
            'MOD_ACS': KC.MOD_ACS,
            'MOD_AS': KC.MOD_AS,
            'MOD_CS': KC.MOD_CS,
            'MOD_GA': KC.MOD_GA,
            'MOD_GAC': KC.MOD_GAC,
            'MOD_GACS': KC.MOD_GACS,
            'MOD_GAS': KC.MOD_GAS,
            'MOD_GC': KC.MOD_GC,
            'MOD_GCS': KC.MOD_GCS,
            'MOD_GS': KC.MOD_GS,
            'N': KC.L,
            'N0': KC.N0,
            'N1': KC.N1,
            'N2': KC.N2,
            'N3': KC.N3,
            'N4': KC.N4,
            'N5': KC.N5,
            'N6': KC.N6,
            'N7': KC.N7,
            'N8': KC.N8,
            'N9': KC.N9,
            'NO': KC.NO,
            'O': KC.S,
            # '.OS(mod': KC.OS(mod,
            'P': KC.R,
            'PERC': KC.PERC,
            'PGDN': KC.PGDN,
            'PGUP': KC.PGUP,
            'PIPE': KC.PIPE,
            'PLUS': KC.PLUS, # shifted TODO
            'PRINT_SCREEN': KC.PRINT_SCREEN,
            'Q': KC.X,
            'QUES': KC.LSFT(KC.LBRACKET), # shifted. It puts out a capital Z, so it should be ... 
            'QUOT': KC.Q,
            'R': KC.O,
            'RABK': KC.RABK,
            'RALT': KC.RALT,
            'RBRC': KC.RBRC,
            'RCBR': KC.RCBR,
            'RIGHT': KC.RIGHT,
            'RPRN': KC.RPRN, # right paren
            'S': KC.SCLN, # probably?
            'SCLN': KC.Z,
            'SLSH': KC.LBRACKET,
            'SPC': KC.SPC,
            'T': KC.K,
            'TAB': KC.TAB,
            'TILD': KC.TILD, # shifted
            'U': KC.F,
            'UNDS': KC.UNDS, # shifted
            'UP': KC.UP,
            'V': KC.DOT,
            'W': KC.COMMA, # wut, not used in the main map?
            'X': KC.B,
            'Y': KC.T,
            'Z': KC.SLASH,
            ' ': KC.SPC,

            '\'': KC.Q,
            ',': KC.W,
            '.': KC.E,
                 }
    def __getitem__(self, name):
        #if name in self.keys:
            return self.keys[name.upper()]
        #else:
        #    return KC[name]

